I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 251, in script
    d " 죄송합니다…제가 무례했네여"
Exception: Sayer 'd' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 251, in script
    d " 죄송합니다…제가 무례했네여"
  File "C:\Users\uSER\renpy-8.1.1-sdk\renpy\ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\uSER\renpy-8.1.1-sdk\renpy\ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'd' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.1.23060707
kaistmossolescape 1.0
Mon Jul 17 13:46:34 2023
